version: '3.8'

services:
  canary:
    image: ${CANARY_IMAGE}
    ports:
      - '3001:${APP_PORT}'
    networks:
      - redis-network
      - monitoring-network
    restart: unless-stopped
    environment:
      - LOG_PATH=/app
      - TEMP_DIR=/tmp/app-logs
      - CANARY_DEPLOYMENT=true
      - CANARY_WEIGHT=${CANARY_WEIGHT}
    env_file:
      - .env
      - .env.deployment
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.canary.rule=Host(`${DROPLET_IP}`)'
      - 'traefik.http.services.canary.loadbalancer.server.port=${APP_PORT}'
      - 'traefik.http.routers.canary.entrypoints=web'
      # Add a unique path for canary to avoid rule conflicts with main app
      - 'traefik.http.routers.canary.priority=2'

  traefik:
    image: traefik:v2.8
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--providers.docker.network=monitoring-network'
      - '--accesslog=true'
      - '--log.level=DEBUG'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - redis-network
      - monitoring-network
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      # Properly define the weighted service middleware
      - 'traefik.http.middlewares.canary-splitter.weighted.services[0].name=app'
      - 'traefik.http.middlewares.canary-splitter.weighted.services[0].weight=${STABLE_WEIGHT:-80}'
      - 'traefik.http.middlewares.canary-splitter.weighted.services[1].name=canary'
      - 'traefik.http.middlewares.canary-splitter.weighted.services[1].weight=${CANARY_WEIGHT:-20}'
      # Apply the middleware to the main entrypoint router
      - 'traefik.http.routers.main.rule=Host(`${DROPLET_IP}`)'
      - 'traefik.http.routers.main.entrypoints=web'
      - 'traefik.http.routers.main.middlewares=canary-splitter'
      - 'traefik.http.routers.main.service=app@docker'
      - 'traefik.http.routers.main.priority=1'

networks:
  redis-network:
    external: true
  monitoring-network:
    external: true