version: '3.8'

services:
  canary:
    image: ${CANARY_IMAGE}
    ports:
      - '3001:${APP_PORT}'
    networks:
      - redis-network
      - monitoring-network
    restart: unless-stopped
    environment:
      - LOG_PATH=/app
      - TEMP_DIR=/tmp/app-logs
      - CANARY_DEPLOYMENT=true
      - CANARY_WEIGHT=${CANARY_WEIGHT}
    env_file:
      - .env
      - .env.deployment
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.canary.rule=Host(`${DROPLET_IP}`)'
      - 'traefik.http.services.canary.loadbalancer.server.port=${APP_PORT}'
      - 'traefik.http.routers.canary.entrypoints=web'
      - 'traefik.http.routers.canary.service=canary'

  traefik:
    image: traefik:v2.8
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--providers.docker.network=monitoring-network'
      - '--accesslog=true'
      - '--log.level=DEBUG'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/opt/app/traefik/traefik.yml:ro
    networks:
      - redis-network
      - monitoring-network
    restart: unless-stopped
    labels:
      - 'traefik.http.middlewares.canary-splitter.traffic.split.service=app'
      - 'traefik.http.middlewares.canary-splitter.traffic.split.service=canary'
      - 'traefik.http.middlewares.canary-splitter.traffic.split.terminating=true'
      - 'traefik.http.routers.app.middlewares=canary-splitter@docker'

networks:
  redis-network:
    external: true
  monitoring-network:
    external: true