version: '3.8'

services:
  canary:
    image: ${CANARY_IMAGE}
    container_name: canary
    ports:
      - '3001:3000'  # Different port to avoid conflict with main app
    networks:
      - redis-network
      - monitoring-network
      - traefik_default
    restart: unless-stopped
    env_file:
      - .env
      - .env.deployment
    environment:
      - APP_PORT=3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.canary.loadbalancer.server.port=3000"
      - "traefik.http.services.canary.loadbalancer.server.scheme=http"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.canary.rule=Host(`${DROPLET_IP}`) || PathPrefix(`/`)"
      - "traefik.http.routers.canary.entrypoints=web"
      - "traefik.http.routers.canary.service=canary@docker"