networks:
  redis-network:
    driver: bridge
  monitoring-network:
    driver: bridge

services:
  app:
    build:
      context: .
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - redis-network
      - monitoring-network
    restart: unless-stopped
    env_file:
      - .env

  redis-master:
    image: redis/redis-stack:latest
    command: ['/scripts/init-master.sh']
    ports:
      - '${REDIS_MASTER_PORT}:6379'
    networks:
      - redis-network
    volumes:
      - redis-data:/data
      - ./backup:/backup
      - ./scripts/init-master.sh:/scripts/init-master.sh:ro
    healthcheck:
      test:
        ['CMD', 'bash', '-c', 'redis-cli -a ${REDIS_PASSWORD} ping | grep PONG']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    profiles:
      - production
      - development

  redis-slave-1:
    image: redis/redis-stack:latest
    command: ['/scripts/init-slave.sh']
    depends_on:
      redis-master:
        condition: service_healthy
    ports:
      - '${REDIS_SLAVE_1_PORT}:6379'
    networks:
      - redis-network
    volumes:
      - ./scripts/init-slave.sh:/scripts/init-slave.sh:ro
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always
    profiles:
      - production
      - development

  redis-slave-2:
    image: redis/redis-stack:latest
    command: ['/scripts/init-slave.sh']
    depends_on:
      redis-master:
        condition: service_healthy
    ports:
      - '${REDIS_SLAVE_2_PORT}:6379'
    networks:
      - redis-network
    volumes:
      - ./scripts/init-slave.sh:/scripts/init-slave.sh:ro
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always
    profiles:
      - production
      - development

      # Add Redis exporters
  redis-exporter-master:
    image: oliver006/redis_exporter
    container_name: redis-exporter-master
    environment:
      - REDIS_ADDR=redis://redis-master:6379
      # - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - redis-network
      - monitoring-network
    ports:
      - "9121:9121"
    restart: unless-stopped
    profiles:
      - production

  redis-exporter-slave1:
    image: oliver006/redis_exporter
    container_name: redis-exporter-slave1
    environment:
      - REDIS_ADDR=redis://redis-slave-1:6379
      # - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - redis-network
      - monitoring-network
    ports:
      - "9122:9121"  # Expose internal port 9121 on host port 9122
    restart: unless-stopped
    profiles:
      - production

  redis-exporter-slave2:
    image: oliver006/redis_exporter
    container_name: redis-exporter-slave2
    environment:
      - REDIS_ADDR=redis://redis-slave-2:6379
      # - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - redis-network
      - monitoring-network
    ports:
      - "9123:9121"  # Expose internal port 9121 on host port 9123
    restart: unless-stopped
    profiles:
      - production

  sentinel-1:
    image: bitnami/redis-sentinel:latest
    environment:
      - REDIS_MASTER_NAME=${REDIS_MASTER_NAME}
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_MASTER_HOST=redis-master
      - REDIS_SENTINEL_QUORUM=${REDIS_SENTINEL_QUORUM}
      - REDIS_SENTINEL_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=180000
      - REDIS_SENTINEL_ANNOUNCE_HOSTNAMES=yes
    ports:
      - '${SENTINEL_1_PORT}:26379'
    networks:
      - redis-network
    restart: always
    profiles:
      - production
      - development

  sentinel-2:
    image: bitnami/redis-sentinel:latest
    environment:
      - REDIS_MASTER_NAME=${REDIS_MASTER_NAME}
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_MASTER_HOST=redis-master
      - REDIS_SENTINEL_QUORUM=${REDIS_SENTINEL_QUORUM}
      - REDIS_SENTINEL_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=180000
      - REDIS_SENTINEL_ANNOUNCE_HOSTNAMES=yes
    ports:
      - '${SENTINEL_2_PORT}:26379'
    networks:
      - redis-network
    restart: always
    profiles:
      - production
      - development

  sentinel-3:
    image: bitnami/redis-sentinel:latest
    environment:
      - REDIS_MASTER_NAME=${REDIS_MASTER_NAME}
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_MASTER_HOST=redis-master
      - REDIS_SENTINEL_QUORUM=${REDIS_SENTINEL_QUORUM}
      - REDIS_SENTINEL_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=180000
      - REDIS_SENTINEL_ANNOUNCE_HOSTNAMES=yes
    ports:
      - '${SENTINEL_3_PORT}:26379'
    networks:
      - redis-network
    restart: always
    profiles:
      - production
      - development

  redis-backup:
    image: alpine
    volumes:
      - redis-data:/data
      - ./backup:/backup
      - ./scripts/backup.sh:/scripts/backup.sh:ro
    networks:
      - redis-network
    entrypoint: ['/bin/sh', '/scripts/backup.sh']
    profiles:
      - production
      - development

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - monitoring-network
      - redis-network
    restart: unless-stopped
    profiles:
      - production

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3005:3000"  # Map Grafana container port 3000 to host port 3005
    networks:
      - monitoring-network
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    profiles:
      - production

volumes:
  redis-data:
  grafana-data:
