version: '3.8'

services:
  canary:
    image: ${CANARY_IMAGE}
    ports:
      - '3001:${APP_PORT}'
    networks:
      - redis-network
      - monitoring-network
    restart: unless-stopped
    environment:
      - LOG_PATH=/app
      - TEMP_DIR=/tmp/app-logs
      - CANARY_DEPLOYMENT=true
      - CANARY_WEIGHT=${CANARY_WEIGHT}
    env_file:
      - .env
      - .env.deployment
    labels:
      - 'traefik.enable=true'
      # Define canary service
      - 'traefik.http.services.canary-service.loadbalancer.server.port=${APP_PORT}'
      # We won't use a separate router for canary - it will be accessed via the weighted service

  traefik:
    image: traefik:v2.8
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--providers.docker.network=monitoring-network'
      - '--accesslog=true'
      - '--log.level=DEBUG'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - redis-network
      - monitoring-network
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      # Define the middleware for canary traffic splitting
      - 'traefik.http.middlewares.canary-splitter.weighted.services[0].name=app-service'
      - 'traefik.http.middlewares.canary-splitter.weighted.services[0].weight=${STABLE_WEIGHT:-80}'
      - 'traefik.http.middlewares.canary-splitter.weighted.services[1].name=canary-service'
      - 'traefik.http.middlewares.canary-splitter.weighted.services[1].weight=${CANARY_WEIGHT:-20}'
      
      # Create the main router - use a catch-all pattern instead of Host rule to start
      - 'traefik.http.routers.main-router.rule=PathPrefix(`/`)'
      - 'traefik.http.routers.main-router.entrypoints=web'
      - 'traefik.http.routers.main-router.middlewares=canary-splitter'
      - 'traefik.http.routers.main-router.priority=1'

networks:
  redis-network:
    external: true
  monitoring-network:
    external: true