version: '3.8'

networks:
  redis-network:
    external: true

services:
  nextjs-app-stable:
    image: ghcr.io/${GITHUB_REPOSITORY_LOWERCASE}:live-latest
    container_name: nextjs-app-stable
    ports:
      - "3001:${APP_PORT:-3000}"
    networks:
      - redis-network
    restart: unless-stopped
    env_file:
      - .env

  nextjs-app-canary:
    image: ghcr.io/${GITHUB_REPOSITORY_LOWERCASE}:live-${GITHUB_SHA}
    container_name: nextjs-app-canary
    ports:
      - "3002:${APP_PORT:-3000}"
    networks:
      - redis-network
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - IS_CANARY=true