global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape the application (Next.js) metrics on port 3000
  - job_name: 'app'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['app:3000']

  # Scrape Grafana metrics (if enabled) on /metrics endpoint
  - job_name: 'grafana'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['grafana:3000']

  # Scrape Redis metrics from master and slaves (adjust port if necessary)
  - job_name: 'redis'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          [
            'redis-exporter-master:9121',
            'redis-exporter-slave1:9121',
            'redis-exporter-slave2:9121',
            'redis-exporter-slave3:9121',
            'redis-exporter-slave4:9121',
          ]
