global:
  scrape_interval: 15s  # How frequently to scrape targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'nextjs-app'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['app:3000']

  # Optional: Scrape Grafana's internal metrics.
  # Grafana exposes metrics on /metrics and listens on port 3000 inside the container.
  # Uncomment the block below if you have enabled Grafana metrics.
  - job_name: 'grafana'
    metrics_path: /metrics
    static_configs:
      - targets: ['grafana:3005']
