http:
  routers:
    app:
      rule: "Host(`${DROPLET_IP}`)"
      service: "app"
      entryPoints:
        - "web"

    canary:
      rule: "Host(`${DROPLET_IP}`)"
      service: "canary"
      entryPoints:
        - "web"

  services:
    app:
      loadBalancer:
        servers:
          - url: "http://app:${APP_PORT}"

    canary:
      loadBalancer:
        servers:
          - url: "http://canary:${APP_PORT}"

  middlewares:
    canary-splitter:
      plugin:
        trafficSplit:
          service1:
            service: "app"
            weight: 80
          service2:
            service: "canary"
            weight: 20