http:
  routers:
    app:
      rule: "Host(`${DROPLET_IP}`)"
      service: "app"
      entryPoints:
        - "web"
      middlewares:
        - "canary-splitter"

    canary:
      rule: "Host(`${DROPLET_IP}`)"
      service: "canary"
      entryPoints:
        - "web"

  services:
    app:
      loadBalancer:
        servers:
          - url: "http://app:${APP_PORT}"

    canary:
      loadBalancer:
        servers:
          - url: "http://canary:${APP_PORT}"

  middlewares:
    canary-splitter:
      trafficSplit:
        services:
          - name: "app"
            weight: $((100-${CANARY_WEIGHT}))
          - name: "canary"
            weight: ${CANARY_WEIGHT}