
name: Build Docker Image
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set repository name lower-case
        id: repo
        run: |
          repo=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          echo "repo=${repo}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Build and Push Docker Image
        if: github.ref == 'refs/heads/dev'
        id: build-staging
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          push: true
          tags: 'ghcr.io/${{ steps.repo.outputs.repo }}:staging-latest'
          cache-from: type=gha
          cache-to: 'type=gha,mode=max'

      - name: Build and Push Docker Image (Live)
        if: github.ref == 'refs/heads/main'
        id: build-live
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.repo }}:live-latest
            ghcr.io/${{ steps.repo.outputs.repo }}:live-${{ github.sha }}
          cache-from: type=gha
          cache-to: 'type=gha,mode=max'
