name: Rollback Canary Deployment
on:
  workflow_call:

jobs:
  rollback:
    runs-on: ubuntu-latest
    name: Rollback Canary Deployment
    steps:
      - name: Rollback to Stable Version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIVE_HOST }}
          username: ${{ secrets.LIVE_USER }}
          key: ${{ secrets.LIVE_SSH_KEY }}
          script: |
            set -euo pipefail
            cd /home/${{ secrets.LIVE_USER }}/app

            echo "Deployment failed! Rolling back to stable version..."

            # Update nginx configuration to direct all traffic to stable
            cat <<EOF | sudo tee /etc/nginx/conf.d/nextjs-app.conf
            upstream nextjs_app {
                server 127.0.0.1:3001;
            }

            server {
                listen 80;
                
                location / {
                    proxy_pass http://nextjs_app;
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                }
            }
            EOF

            # Reload nginx
            sudo nginx -t && sudo systemctl reload nginx

            # Clean up the canary container
            docker-compose stop app-canary || true
            docker-compose rm -f app-canary || true

            echo "Rollback completed successfully."
