name: Security Scanning

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: false
    outputs:
      security_status:
        description: "Status of security scans"
        value: ${{ jobs.security-scan.outputs.status }}

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    outputs:
      status: ${{ steps.set-output.outputs.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper scanning
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Run yarn audit
        id: yarn-audit
        run: yarn audit --audit-level=high || echo "yarn-audit-failed=true" >> $GITHUB_ENV
        continue-on-error: true  # Don't fail the build yet
      
      - name: Run dependency check
        id: dependency-check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'NextJS-App'
          path: '.'
          format: 'HTML'
          out: 'dependency-reports'
          args: >
            --enableExperimental
            --failOnCVSS 7
        continue-on-error: true  # Don't fail the build yet
      
      - name: Run Trivy filesystem scan
        id: trivy-fs
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          output: 'trivy-fs-results.txt'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true  # Don't fail the build yet
      
      # Using CodeQL v3 instead of v2 as per warning
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"
        continue-on-error: true
          
      - name: Package security reports
        run: |
          mkdir -p security-reports
          
          # Copy dependency check reports if they exist
          if [ -d "dependency-reports" ]; then
            cp -r dependency-reports/* security-reports/ || true
          fi
          
          # Copy Trivy results if they exist
          if [ -f "trivy-fs-results.txt" ]; then
            cp trivy-fs-results.txt security-reports/ || true
          fi
          
          # Create a summary file
          echo "# Security Scan Summary" > security-reports/summary.md
          echo "## Scan performed at $(date)" >> security-reports/summary.md
          echo "### NPM Audit" >> security-reports/summary.md
          if [ "$npm_audit_failed" == "true" ]; then
            echo "- Issues found in NPM audit" >> security-reports/summary.md
          else
            echo "- No critical issues found in NPM audit" >> security-reports/summary.md
          fi
          
          # Ensure we have at least one file to upload
          touch security-reports/.gitkeep
        if: always()
          
      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: security-reports/
          retention-days: 5
        if: always()
      
      - name: Set final output status
        id: set-output
        run: |
          if [[ "$npm_audit-failed" == "true" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "status=failed" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "status=passed" >> $GITHUB_OUTPUT
          fi