name: Security Scanning

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: false
    outputs:
      security_status:
        description: "Status of security scans"
        value: ${{ jobs.security-scan.outputs.status }}

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    outputs:
      status: ${{ steps.set-output.outputs.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper scanning
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run npm audit
        id: npm-audit
        run: npm audit --audit-level=high || echo "npm-audit-failed=true" >> $GITHUB_ENV
        continue-on-error: true  # Don't fail the build yet
      
      - name: Run dependency check
        id: dependency-check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'NextJS-App'
          path: '.'
          format: 'SARIF'
          out: 'reports'
          args: >
            --enableExperimental
            --failOnCVSS 7
        continue-on-error: true  # Don't fail the build yet
            
      - name: Upload dependency check results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'reports/dependency-check-report.sarif'
        if: always()
          
      - name: Run CodeQL Analysis
        id: codeql
        uses: github/codeql-action/analyze@v2
        continue-on-error: true  # Don't fail the build yet
          
      - name: Run Trivy filesystem scan
        id: trivy-fs
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true  # Don't fail the build yet
          
      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
        if: always()
          
      - name: Package security report
        run: |
          mkdir -p security-reports
          cp reports/* security-reports/ || true
          cp trivy-results.sarif security-reports/ || true
        if: always()
          
      - name: Upload security reports
        # Updated to latest version with current syntax
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: security-reports/
          retention-days: 5
        if: always()
      
      - name: Set final output status
        id: set-output
        run: |
          if [[ "$npm_audit_failed" == "true" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "status=failed" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "status=passed" >> $GITHUB_OUTPUT
          fi